version: '3'
services:
  ununifi-explorer:
    container_name: ununifi-explorer
    image: ghcr.io/ununifi/explorer:test
    volumes:
      - ./config.js:/usr/share/nginx/html/assets/config.js
      - ./config.js:/usr/share/nginx/html/ununifi/assets/config.js
      - ./nginx.conf:/etc/nginx/nginx.conf
    # ports:
    #   - 80:80
    network_mode: host
    restart: always
