version: '3'

services:
  telescope:
    container_name: marketplace
    image: ghcr.io/ununifi/marketplace
    # build:
    #   dockerfile: ./Dockerfile
    volumes:
      - ./config.js:/usr/share/nginx/html/assets/config.js
      - ./nginx.conf:/etc/nginx/nginx.conf
    # ports:
    #   - 80:80
    network_mode: host
    restart: always
