name: CD Firebase ununifi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Cache angular build
        uses: actions/cache@v3
        with:
          path: .angular/cache
          key: angular-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - run: npm run build:all:prod:ununifi
      - run: npx firebase deploy --only hosting:ununifi --project=default --token=${{ secrets.FIREBASE_TOKEN }}
