name: CI Portal Docker image
on:
  workflow_dispatch:
  ## disable Github Action related to Docker.
  # pull_request:
  #   paths:
  #     - 'projects/portal/**'
  #     - 'projects/shared/**'
jobs:
  push_to_registry:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup variables
        id: variables
        run: echo "::set-output name=version::${GITHUB_REF##*/}"
      - name: Build only
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./projects/portal/Dockerfile
          push: false
          tags: |
            ghcr.io/ununifi/portal:${{ steps.variables.outputs.version }}
            ghcr.io/ununifi/portal:latest
