name: Node.js CI shared

on:
  pull_request:
    paths:
      - 'projects/shared/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm i -g npm
      - run: npm ci
      - run: npm run build --if-present -- --project=shared
        # Todo: after implementation of testing, this should be enabled.
        # - run: npm run test -- --project=shared
        env:
          CI: true
