name: Node.js CI marketplace
on:
  pull_request:
    paths:
      - 'projects/marketplace/**'
      - 'projects/shared/**'
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # - run: npm i -g npm
      - run: npm ci
      - run: npm run build --if-present -- --project=marketplace
      - run: npm run test -- --project=marketplace
        env:
          CI: true
