version: '3'
services:
  ununifi-portal:
    container_name: ununifi-portal
    image: ghcr.io/ununifi/portal
    volumes:
      - ./config.js:/usr/share/nginx/html/assets/config.js
      - ./nginx.conf:/etc/nginx/nginx.conf
    # ports:
    #   - 80:80
    network_mode: host
    restart: always
